version: "3.8"

services:
  app:
    build: ../app
    volumes:
      - ./logs:/var/log/app
    ports:
      - "5000:5000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  loki:
    image: grafana/loki:2.9.1
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki/config.yml:/etc/loki/loki-config.yml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.1
    volumes:
      - /var/log:/var/log
      - /etc/machine-id:/etc/machine-id
      - ./loki/promtail-config.yml:/etc/promtail/config.yml
      - ./logs:/var/log/app
    command: -config.file=/etc/promtail/config.yml

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards.yml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
